services:
  n8nio:
    image: phyjim/qc-n8n:latest
    ports:
      - '5001:5678'
    container_name: n8n
    restart: unless-stopped
    networks:
      - web
  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - "5002:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Zos38586
    volumes:
      - ./pgdb-data:/var/lib/postgresql/data
    networks:
      - web
  image-server:
    image: phyjim/image-server:latest
    ports:
      - "5003:8000"
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
      - DB_NAME=qc
      - DB_USER=admin
      - DB_PASSWORD=Zos38586
    networks:
      - web

  web-cam:
    image: phyjim/web-cam:latest
    restart: always
    ports:
      - "5004:80"
    networks:
      - web

networks:
  web: 
    driver: bridge